version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=people_db
     - POSTGRES_USER=people
     - POSTGRES_PASSWORD=people
     - MAX_CONNECTIONS=300
